# Generated by Django 3.2.20 on 2023-08-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='LegoSet',
        ),
        migrations.DeleteModel(
            name='LegoSetTheme',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
