# Generated by Django 3.2.20 on 2023-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
